# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir:  
  base: /Users/alessiobocco/Documents/GitHub/series_cortas/IdentificarEventos
  run: /Users/alessiobocco/Documents/GitHub/series_cortas/IdentificarEventos/run/
  indices.sequia:
    run: /Users/alessiobocco/Documents/GitHub/series_cortas/IndicesSequia/run/
  lib: /Users/alessiobocco/Documents/GitHub/series_cortas/lib/R/
  data: /Users/alessiobocco/Documents/GitHub/series_cortas/data/
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Cantidad maxima de procesos paralelos
# ------------------------------------------------------------------------------
max.procesos: 8
# ------------------------------------------------------------------------------
