
# ------------------------------------------------------------------------------
# Acceso a la API
# ------------------------------------------------------------------------------
api:
  url: 'https://api.crc-sas.org/ws-api'
  user: 'clima' 
  pass: 'Dcft^&*('
# ------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------
# Datos de acceso a base de datos
# -----------------------------------------------------------------------------------
db:
  name: crcssa
  host: localhost
  port: 5432
  user: alessiobocco
  password: ${db.password}
# -----------------------------------------------------------------------------------
