# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir:  
  base: "/Users/alessiobocco/Documents/GitHub/series_cortas/IndicesSequia"
  data: "/Users/alessiobocco/Documents/GitHub/series_cortas/data"
# ------------------------------------------------------------------------------
