# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir:  
  base: "/Users/alessiobocco/Programacion/R/SISSA/devel/series_cortas/indices-eventos/EstadisticasMoviles"
  run: "/Users/alessiobocco/Programacion/R/SISSA/devel/series_cortas/indices-eventos/EstadisticasMoviles/run"
  lib: "/Users/alessiobocco/Programacion/R/SISSA/devel/series_cortas/indices-eventos/lib/R"
  data: "/Users/alessiobocco/Programacion/R/SISSA/devel/series_cortas/indices-eventos/data"
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Cantidad maxima de procesos paralelos
# ------------------------------------------------------------------------------
max.procesos: 8
# ------------------------------------------------------------------------------
